In [2]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import uproot

In [3]:
file = uproot.open("starting_ntuples/SSWW_polarized_WWrf.root")
file.classnames()

{'trees;1': 'TDirectory',
 'trees/ssww;1': 'TDirectory',
 'trees/ssww/SSWW_WWrf_LL;1': 'TDirectory',
 'trees/ssww/SSWW_WWrf_LL/Events;1': 'TTree',
 'trees/ssww/SSWW_WWrf_TL;1': 'TDirectory',
 'trees/ssww/SSWW_WWrf_TL/Events;1': 'TTree',
 'trees/ssww/SSWW_WWrf_TT;1': 'TDirectory',
 'trees/ssww/SSWW_WWrf_TT/Events;1': 'TTree',
 'ssww;1': 'TDirectory'}

In [4]:
events_LL = uproot.open("starting_ntuples/SSWW_polarized_WWrf.root:trees/ssww/SSWW_WWrf_LL/Events")
events_LL

<TTree 'Events' (36 branches) at 0x01acb193c490>

In [5]:
events_LL.keys()

['XSWeight',
 'nCleanJet',
 'CleanJet_pt',
 'CleanJet_eta',
 'CleanJet_phi',
 'CleanJet_mass',
 'ptj1',
 'ptj2',
 'etaj1',
 'etaj2',
 'phij1',
 'phij2',
 'mj1',
 'mj2',
 'mjj',
 'detajj',
 'ptl1',
 'ptl2',
 'etal1',
 'etal2',
 'phil1',
 'phil2',
 'pdgIdl1',
 'pdgIdl2',
 'mll',
 'ptMET',
 'phiMET',
 'ptv1',
 'ptv2',
 'etav1',
 'etav2',
 'phiv1',
 'phiv2',
 'pdgIdv1',
 'pdgIdv2',
 'weight']

In [6]:
events_LL.values()

[<TBranch 'XSWeight' at 0x01acb3260c10>,
 <TBranch 'nCleanJet' at 0x01acb2bde150>,
 <TBranch 'CleanJet_pt' at 0x01acb37fb1d0>,
 <TBranch 'CleanJet_eta' at 0x01acb37fc790>,
 <TBranch 'CleanJet_phi' at 0x01acb37fd850>,
 <TBranch 'CleanJet_mass' at 0x01acb37fe8d0>,
 <TBranch 'ptj1' at 0x01acb37fecd0>,
 <TBranch 'ptj2' at 0x01acb38081d0>,
 <TBranch 'etaj1' at 0x01acb3809a10>,
 <TBranch 'etaj2' at 0x01acb37fe4d0>,
 <TBranch 'phij1' at 0x01acb380bb10>,
 <TBranch 'phij2' at 0x01acb380cbd0>,
 <TBranch 'mj1' at 0x01acb380dd10>,
 <TBranch 'mj2' at 0x01acb380ed90>,
 <TBranch 'mjj' at 0x01acb380fe10>,
 <TBranch 'detajj' at 0x01acb381cf90>,
 <TBranch 'ptl1' at 0x01acb381e010>,
 <TBranch 'ptl2' at 0x01acb381f110>,
 <TBranch 'etal1' at 0x01acb3824190>,
 <TBranch 'etal2' at 0x01acb3825250>,
 <TBranch 'phil1' at 0x01acb38262d0>,
 <TBranch 'phil2' at 0x01acb3827310>,
 <TBranch 'pdgIdl1' at 0x01acb382c390>,
 <TBranch 'pdgIdl2' at 0x01acb382d3d0>,
 <TBranch 'mll' at 0x01acb382e490>,
 <TBranch 'ptMET' at 0

In [7]:
events_LL.show()

name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
XSWeight             | float                    | AsDtype('>f4')
nCleanJet            | uint32_t                 | AsDtype('>u4')
CleanJet_pt          | float[]                  | AsJagged(AsDtype('>f4'))
CleanJet_eta         | float[]                  | AsJagged(AsDtype('>f4'))
CleanJet_phi         | float[]                  | AsJagged(AsDtype('>f4'))
CleanJet_mass        | float[]                  | AsJagged(AsDtype('>f4'))
ptj1                 | float                    | AsDtype('>f4')
ptj2                 | float                    | AsDtype('>f4')
etaj1                | float                    | AsDtype('>f4')
etaj2                | float                    | AsDtype('>f4')
phij1                | float                    | AsDtype('>f4')
phij2                | float                    | AsDtype('>f4')
mj1               

In [8]:
events_LL.keys(filter_typename='float'or'uint32_t'or'double')

['XSWeight',
 'ptj1',
 'ptj2',
 'etaj1',
 'etaj2',
 'phij1',
 'phij2',
 'mj1',
 'mj2',
 'mjj',
 'detajj',
 'ptl1',
 'ptl2',
 'etal1',
 'etal2',
 'phil1',
 'phil2',
 'pdgIdl1',
 'pdgIdl2',
 'mll',
 'ptMET',
 'phiMET',
 'ptv1',
 'ptv2',
 'etav1',
 'etav2',
 'phiv1',
 'phiv2',
 'pdgIdv1',
 'pdgIdv2']

In [9]:
mjj = events_LL['mjj'].array(library='np')
mjj

array([ 717.575  , 1749.2535 , 2111.3267 , ...,  825.49927, 2489.5225 ,
       2268.8162 ], dtype=float32)

In [10]:
data = events_LL.arrays(library='pd')
for x  in data['ptl1']:
    #print(x)
    if x < 25: print('help')

In [11]:
#

In [12]:
a = [-10, 1, 2]
b = [1, -2, 3]
c = [True, False, True]
for i in range(3):
    print(np.where(c[i], a, b))

[-10   1   2]
[ 1 -2  3]
[-10   1   2]


In [13]:
#

In [14]:
file.close()

In [15]:
file = open('test.txt', 'r')

file.readline()

id1, id2 = file.readline().split()
id1 = int(id1)
id2 = int(id2)
print(id1, id2)

mask = np.zeros(5)
mask[id1] = 1
mask[id2] = 1
print(mask)
file.close()

2 3
[0. 0. 1. 1. 0.]


In [16]:
arr = list(range(5))
np.where(mask, arr, np.zeros(5))

array([0., 0., 2., 3., 0.])

In [17]:
#

In [19]:
jetPt_nvbs = np.stack([[1, 0, 0],[1, 1, 0]], axis=1)
mask_pad = jetPt_nvbs > 0.
jetPt_nvbs[mask_pad]

array([1, 1, 1])